-- MySQL Script generated by MySQL Workbench
-- 02/15/17 20:33:28
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fca
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `fca` ;

-- -----------------------------------------------------
-- Schema fca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fca` DEFAULT CHARACTER SET latin1 COLLATE latin1_general_cs ;
USE `fca` ;

-- -----------------------------------------------------
-- Table `fca`.`equipamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fca`.`equipamentos` ;

CREATE TABLE IF NOT EXISTS `fca`.`equipamentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `radio` VARCHAR(16) NOT NULL,
  `caf` VARCHAR(45) NOT NULL,
  `cod_sap` VARCHAR(45) NULL DEFAULT NULL,
  `descricao` VARCHAR(45) NULL DEFAULT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `fabricante` VARCHAR(45) NOT NULL,
  `ano_fabr` YEAR NULL DEFAULT NULL,
  `ute` VARCHAR(10) NOT NULL,
  `setor` VARCHAR(45) NOT NULL,
  `produto` VARCHAR(45) NULL DEFAULT NULL,
  `operacao` VARCHAR(4) NULL DEFAULT NULL,
  `cons_energia_prod` DECIMAL(10,2) NULL DEFAULT NULL,
  `cons_energia_lig` DECIMAL(10,2) NULL DEFAULT NULL,
  `horimetro` FLOAT NULL DEFAULT NULL,
  `ciclos` FLOAT NULL DEFAULT NULL,
  `data_inicial` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `radio`),
  UNIQUE INDEX `radio_UNIQUE` (`radio` ASC),
  UNIQUE INDEX `caf_UNIQUE` (`caf` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fca`.`evento_tipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fca`.`evento_tipo` ;

CREATE TABLE IF NOT EXISTS `fca`.`evento_tipo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cor` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fca`.`producao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fca`.`producao` ;

CREATE TABLE IF NOT EXISTS `fca`.`producao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATETIME NULL DEFAULT NULL,
  `abastecer` DECIMAL(10,2) NULL DEFAULT NULL,
  `produzir` DECIMAL(10,2) NULL DEFAULT NULL,
  `desabastecer` DECIMAL(10,2) NULL DEFAULT NULL,
  `duracao` DECIMAL(10,2) GENERATED ALWAYS AS ((`abastecer` + `produzir` + `desabastecer`)),
  `equipamentos_radio` VARCHAR(16) NOT NULL,
  `operador` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `equipamentos_radio`),
  INDEX `fk_producao_equipamentos_idx` (`equipamentos_radio` ASC),
  CONSTRAINT `fk_producao_equipamentos`
    FOREIGN KEY (`equipamentos_radio`)
    REFERENCES `fca`.`equipamentos` (`radio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fca`.`controle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fca`.`controle` ;

CREATE TABLE IF NOT EXISTS `fca`.`controle` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `equipamentos_radio` VARCHAR(16) NOT NULL,
  `evento_tipo_id` INT NOT NULL,
  `operador` VARCHAR(10) NULL DEFAULT NULL,
  `inicio` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fim` TIMESTAMP NULL DEFAULT NULL,
  `duracao` DECIMAL(10,2) GENERATED ALWAYS AS (timestampdiff(SECOND,`inicio`,`fim`)) VIRTUAL,
  PRIMARY KEY (`id`, `equipamentos_radio`, `evento_tipo_id`),
  INDEX `fk_controle_equipamentos1_idx` (`equipamentos_radio` ASC),
  INDEX `fk_controle_evento_tipo1_idx` (`evento_tipo_id` ASC),
  CONSTRAINT `fk_controle_equipamentos1`
    FOREIGN KEY (`equipamentos_radio`)
    REFERENCES `fca`.`equipamentos` (`radio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_controle_evento_tipo1`
    FOREIGN KEY (`evento_tipo_id`)
    REFERENCES `fca`.`evento_tipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fca`.`login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fca`.`login` ;

CREATE TABLE IF NOT EXISTS `fca`.`login` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` CHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
